openapi: '3.0.2'
info:
  title: 'Store API'
  description: 'Store API description'
  version: '0.0'
tags:
  - name: Goods
components:
  schemas:
    Good:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        description:
          type: string
        image:
          type: string
        price:
          type: integer
        active:
          type: boolean
        count:
          type: integer
    AddGood:
      type: object
      properties:

        name:
          type: string
        description:
          type: string
        image:
          type: string
          description: base64 encoded string
        price:
          type: integer
        active:
          type: boolean
        count:
          type: integer
paths:
  /api/v1/goods/:
    get:
      summary: Get list of goods
      tags:
        - Goods
      responses:
        '200':
          description: Ok
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Good'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
    post:
      summary: Add good
      tags:
        - Goods
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGood'
      responses:
        '200':
          description: Ok
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
        '400':
          description: bad parametres

        '500':
          description: Internal server error

  /api/v1/goods/{id}:
    get:
      summary: Get good by id
      tags:
        - Goods
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Good'
        '404':
          description: Not found
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
    patch:
      summary: update good fields
      tags:
        - Goods
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGood'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad parameters

    delete:
      summary: delete good
      tags:
        - Goods
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        '200':
          description: Ok
        '400':
          description: Bad parameters
